version: '3'
services:
  mysql:
    container_name: qiita-tagging-db
    image: mysql:8.1.0
    hostname: qiita-tagging-db
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    container_name: "qiita-tagging-phpmyadmin"
    hostname: "qiita-tagging-phpmyadmin"
    image: phpmyadmin/phpmyadmin:5.2.0
    ports:
      - "127.0.0.1:8888:80"
    environment:
      - "PMA_HOST=qiita-tagging-db"
      - "PMA_USER=root"
      - "PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=Asia/Tokyo"
    restart: always
volumes:
  mysql_data_volume:
    name: "qiita-tagging-mysql-volume"
