version: "3"
services:
  go:
    container_name: HackU2023_Nagoya_GO
    build:
      context: ./build/go
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src/app
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 2g
    depends_on:
      - "mysql"

  mysql:
    container_name: HackU2023_Nagoya_DB
    image: mysql:latest
    volumes:
      - ./build/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3309"
    expose:
      - 3309
    deploy:
      resources:
        limits:
          memory: 2g
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hacku_nagoya
      MYSQL_TCP_PORT: 3309

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: HackU2023_Nagoya_Voicevox
    volumes:
      - ./build/voicevox/presets.yaml:/opt/voicevox_engine/presets.yaml
    ports:
      - "50021:50021"
    tty: true
