version: '3'
services:
  go:
    container_name: HackU2023_Nagoya_GO
    build:
      context: ./build/go
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    # env_file:
    #   - ./build/go/.env
    volumes:
      - ./src:/src/app
    ports:
      - 8080:8080
    depends_on:
      - "mysql"

  mysql:
    container_name: HackU2023_Nagoya_DB
    image: mysql:latest
    volumes:
      - build/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hacku_nagoya

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: HackU2023_Nagoya_Voicevox
    ports: 
      - '50021:50021'
    tty: true