set global local_infile = 1;
CREATE DATABASE IF NOT EXISTS db;
USE db;
CREATE TABLE IF NOT EXISTS tag_list(
    id INT NOT NULL AUTO_INCREMENT,
    tag_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE USER IF NOT EXISTS 'user' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON db.* TO 'user';
FLUSH PRIVILEGES;
